In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [18]:
db = pd.read_csv('https://openei.org/doe-opendata/dataset/5346c5c2-be26-4be7-9663-b5a98cbb7527/resource/096347a1-8be8-4df8-87e3-065531f7215f/download/usretechnicalpotential.csv')

In [19]:
db.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 31 columns):
Unnamed: 0                    51 non-null object
urbanUtilityScalePV_GWh       51 non-null int64
urbanUtilityScalePV_GW        51 non-null int64
urbanUtilityScalePV_km2       51 non-null int64
ruralUtilityScalePV_GWh       51 non-null int64
ruralUtilityScalePV_GW        51 non-null int64
ruralUtilityScalePV_km2       51 non-null int64
rooftopPV_GWh                 49 non-null float64
rooftopPV_GW                  51 non-null int64
CSP_GWh                       51 non-null int64
CSP_GW                        51 non-null int64
CSP_km2                       51 non-null int64
onshoreWind_GWh               51 non-null int64
onshoreWind_GW                51 non-null int64
onshoreWind_km2               51 non-null int64
offshoreWind_GWh              29 non-null float64
offshoreWind_GW               29 non-null float64
offshoreWind_km2              29 non-null float64
biopowerSolid_GWh             51 non-null int64
biopowerSolid_GW              51 non-null int64
biopowerSolid_BDT             51 non-null int64
biopowerGaseous_GWh           51 non-null int64
biopowerGaseous_GW            51 non-null int64
biopowerGaseous_Tonnes-CH4    51 non-null int64
geothermalHydrothermal_GWh    51 non-null int64
geothermalHydrothermal_GW     51 non-null int64
EGSGeothermal_GWh             49 non-null float64
EGSGeothermal_GW              49 non-null float64
hydropower_GWh                51 non-null int64
hydropower_GW                 51 non-null int64
hydropower_countOfSites       51 non-null int64
dtypes: float64(6), int64(24), object(1)
memory usage: 12.4+ KB

In [20]:
db.head()

,Unnamed: 0,urbanUtilityScalePV_GWh,urbanUtilityScalePV_GW,urbanUtilityScalePV_km2,ruralUtilityScalePV_GWh,ruralUtilityScalePV_GW,ruralUtilityScalePV_km2,rooftopPV_GWh,rooftopPV_GW,CSP_GWh,...,biopowerGaseous_GWh,biopowerGaseous_GW,biopowerGaseous_Tonnes-CH4,geothermalHydrothermal_GWh,geothermalHydrothermal_GW,EGSGeothermal_GWh,EGSGeothermal_GW,hydropower_GWh,hydropower_GW,hydropower_countOfSites
0,Alabama,35850,20,426,3706838,2114,44058,15475.0,12,0,...,1533,0,326186,0,0,535489.0,67.0,4102,0,2435
1,Alaska,166,0,2,8282976,9005,187608,NaN,1,0,...,61,0,13156,15437,1,NaN,NaN,23675,5,3053
2,Arizona,121305,52,1096,11867693,5147,107230,22736.0,14,12544333,...,837,0,178188,8329,1,1239147.0,157.0,1303,0,1958
3,Arkansas,28960,15,332,4986388,2747,57239,8484.0,6,0,...,1063,0,226178,0,0,628621.0,79.0,6093,1,3268
4,California,246008,111,2320,8855917,4010,83549,106411.0,75,8490916,...,15510,1,3300211,130921,16,1344179.0,170.0,30023,6,9692